version: '3'

services:
  pg:
    networks:
      - notification-network
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

  rabbitmq:
    networks:
      - notification-network
    image: rabbitmq:management
    environment:
      RABBIT_MQ_DEFAULT_USER: "user"
      RABBIT_MQ_DEFAULT_PASS: "pass"
      ports: "15672:15672"


  user-module:
    networks:
      - notification-network
    depends_on:
      - pg
      - rabbitmq
    image: user-module
    build:
      context: ./UserModule

  notification-module:
    networks:
      - notification-network
    depends_on:
      - pg
      - rabbitmq
    image: notification-module
    build:
      context: ./NotificationModule

networks:
  notification-network:

